<a href="https://colab.research.google.com/github/ErickNoGit/Exerc-cios/blob/main/Exercicio_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy: array com linspace**

***Arange***

In [7]:
import numpy as np
array1 = np.arange(10)

In [8]:
array2 = np.arange(10, 20)

In [9]:
array3 = np.arange(10, 20, 2)

In [10]:
array4 = np.arange(10, 20, 1.4)

***Linspace***

In [11]:
array5 = np.linspace(10, 20, 11)
#10, 11, ..., 20(11 elementos)
print(array5)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


In [17]:
array6 = np.linspace(10, 20, 101)
#10, 10.1, ..., 20, (101 elementos)
print(array6)

[10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1 11.2 11.3
 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5 12.6 12.7
 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9 14.  14.1
 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3 15.4 15.5
 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7 16.8 16.9
 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1 18.2 18.3
 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5 19.6 19.7
 19.8 19.9 20. ]


In [18]:
array7 = np.linspace(10, np.pi, 100)
#de 0 até pi, 100 elementos
print(array7)

[10.          9.93072316  9.86144632  9.79216947  9.72289263  9.65361579
  9.58433895  9.51506211  9.44578526  9.37650842  9.30723158  9.23795474
  9.1686779   9.09940106  9.03012421  8.96084737  8.89157053  8.82229369
  8.75301685  8.68374     8.61446316  8.54518632  8.47590948  8.40663264
  8.33735579  8.26807895  8.19880211  8.12952527  8.06024843  7.99097159
  7.92169474  7.8524179   7.78314106  7.71386422  7.64458738  7.57531053
  7.50603369  7.43675685  7.36748001  7.29820317  7.22892632  7.15964948
  7.09037264  7.0210958   6.95181896  6.88254212  6.81326527  6.74398843
  6.67471159  6.60543475  6.53615791  6.46688106  6.39760422  6.32832738
  6.25905054  6.1897737   6.12049685  6.05122001  5.98194317  5.91266633
  5.84338949  5.77411265  5.7048358   5.63555896  5.56628212  5.49700528
  5.42772844  5.35845159  5.28917475  5.21989791  5.15062107  5.08134423
  5.01206738  4.94279054  4.8735137   4.80423686  4.73496002  4.66568318
  4.59640633  4.52712949  4.45785265  4.38857581  4

# **NumPy: matrizes**

In [19]:
minhaMatriz = np.array([[1, 2, 3],
                        [4, 5, 6]])

In [20]:
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

***Podemos criar uma matriz a partir de uma lista:***

In [21]:
minhaLista = [[13, 81, 22], [0, 34, 59], [21, 48, 94]]

***Agora usaremos np.matrix***

In [22]:
minhaMatriz = np.matrix(minhaLista)
minhaMatriz

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

***np.zeros: pode formar vetores e matrizes***

In [26]:
# VETOR
x = np.zeros(3)
x

array([0., 0., 0.])

In [29]:
# MATRIZ (x e y, linhas e colunas)
x = np.zeros((3, 2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

***Sem armazenar em variáveis***

In [32]:
# VETOR
print(np.zeros(3))

[0. 0. 0.]


In [31]:
# MATRIZ
print(np.zeros((3, 2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


***np.ones***

In [33]:
x = np.ones((5,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

### **Desafio: como obter uma matriz 4x4 apenas com números 8?**

In [45]:
x = np.full((4,4), 8)
x

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

***np.diag para formar matrizes***

In [49]:
z = np.diag(np.array([1, 2, 3, 4, 5, 6]))
#os valores passados como parâmetro formam uma diagonal
z

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

***np.eye para formar matrizes***

In [51]:
y = np.eye(5)
#5 linhas e 5 colunas de 1 em diagonal no float
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
y = np.eye(5, dtype= int)
#mesmo formato, porém com inteiros
y

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# **NumPy: shape**

In [54]:
np.shape(minhaMatriz)

(3, 3)

In [55]:
minhaMatriz.shape

(3, 3)

# **NumPy: tipo**

In [56]:
type(minhaMatriz)

numpy.matrix

In [57]:
minhaMatriz.dtype

dtype('int64')

# **NumPy: matrizes selecionando elementos**

In [58]:
minhaMatriz[2, 1]

48

In [60]:
print(minhaMatriz[0,:])

[[13 81 22]]


In [61]:
print(minhaMatriz[:,2])

[[22]
 [59]
 [94]]


In [62]:
minhaMatriz[1,0] = 100
minhaMatriz

matrix([[ 13,  81,  22],
        [100,  34,  59],
        [ 21,  48,  94]])

# **NumPy: operações básicas**

In [65]:
#Obtendo a soma dos valores do array:
meuArray = [array1, array2]
np.sum(meuArray)

190

In [66]:
#Obtendo o produto:
np.prod(meuArray)

0

In [67]:
#Obtendo a soma acumulada:
np.cumsum(meuArray)

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190])

In [72]:
#Obtendo o valor mínimo do array:
array1.min()

0

In [73]:
#Obtendo o valor máximo:
array1.max()

9

# **NumPy: operações com estatística básica**

In [74]:
#Obtendo a média dos valores do array:
np.mean(meuArray)

9.5

In [75]:
#Obtendo a mediana:
np.median(meuArray)

9.5

In [76]:
#Obtendo a variância dos valores:
np.var(meuArray)

33.25

In [77]:
#Obtendo o desvio padrão dos valores:
np.std(meuArray)

5.766281297335398

# **NumPy: matrizes**

In [90]:
"""
Desafio
Criar um array unidimensional usando arange com 20 elementos;
● “Varrer” o array para obter os pares;
● “Varrer” o array para obter os ímpares;
● Obter a média, a soma, o produto, a variância e o desvio padrão
do array.
● Saber se os valores são maiores que 5;
● Obter os valores maiores que 5.
"""
arrayX = np.arange(20)
print("pares:",arrayX[::2])
print("ímpares:",arrayX[1::2])
print("média:",np.mean(arrayX))
print("soma:",np.sum(arrayX))
print("produto:",np.prod(arrayX))
print("variância:",np.var(arrayX))
print("desvio:",np.std(arrayX))
print(arrayX > 5)
print(arrayX[6:])

pares: [ 0  2  4  6  8 10 12 14 16 18]
ímpares: [ 1  3  5  7  9 11 13 15 17 19]
média: 9.5
soma: 190
produto: 0
variância: 33.25
desvio: 5.766281297335398
[False False False False False False  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]
